#!/usr/local/cs/bin/python3

import sys

timeZones = [
    "-1100", "-1000", "-0900", "-0800", "-0700", "-0600",
    "-0500", "-0400", "-0300", "-0200", "-0100", "-0000",
    "+0000", "+0100", "+0200", "+0300", "+0400", "+0500",
    "+0600", "+0700", "+0800", "+0900", "+1000", "+1100",
    "+1200"
]


counts = {zone: 0 for zone in timeZones}

for line in sys.stdin:
    zone = line.strip()[-5:]
    if zone in counts:
        counts[zone] += 1

for zone, count in counts.items():
    if count != 0:
        print(f"{zone} {count}")